name: aws_sdk_android
description: "Android implementation of the aws_sdk plugin."
version: 0.0.1-dev.1
repository: "https://github.com/yanshouwang/aws_sdk"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  aws_sdk_platform_interface: ^0.0.1-dev.1
  jni: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  jnigen: ^0.10.0

flutter:
  plugin:
    implements: aws_sdk_flutter
    platforms:
      android:
        package: dev.hebei.aws_sdk_android
        pluginClass: AWSSDKAndroidPlugin
        dartPluginClass: AWSSDKAndroidPlugin
