name: aws_sdk_platform_interface
description: "A common platform interface for the aws_sdk plugin."
version: 0.0.1-dev.1
repository: "https://github.com/yanshouwang/aws_sdk"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  test: ^1.25.8
  lints: ^4.0.0
