name: aws_sdk_flutter
description: "Develop and deploy applications with the AWS SDK for Flutter. The SDK makes it easy to call AWS services using idiomatic Flutter APIs."
version: 0.0.1-dev.1
repository: "https://github.com/yanshouwang/aws_sdk"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aws_sdk_platform_interface: ^0.0.1-dev.1
  aws_sdk_android: ^0.0.1-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: aws_sdk_android
      # ios:
      #   default_package: aws_sdk_darwin
      # macos:
      #   default_package: aws_sdk_darwin
      # windows:
      #   default_package: aws_sdk_windows
      # linux:
      #   default_package: aws_sdk_linux
      # web:
      #   default_package: aws_sdk_web
