name: aws_sdk
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  aws_sdk_platform_interface:
    path: ../aws_sdk_platform_interface
  aws_sdk_android:
    path: ../aws_sdk_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: aws_sdk_android
      # ios:
      #   default_package: aws_sdk_darwin
      # macos:
      #   default_package: aws_sdk_darwin
      # windows:
      #   default_package: aws_sdk_windows
      # linux:
      #   default_package: aws_sdk_linux
      # web:
      #   default_package: aws_sdk_web
